name: Deploy

on:
  push:
    branches: [ feature ]

jobs:

  generate-apk: # Job to generate debug apk
    name: ⚙️Generate APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build debug apk
        run: ./gradlew clean assembleDebug --stacktrace

  create-release: # Job to create a new github release and upload the generated apk
    name: 🎉 Create Release
    needs: [ generate-apk ]
    runs-on: ubuntu-latest
    steps:

      - name: Create release
        uses: ShaunLWM/action-release-debugapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} # Environment secret -GitHub Token
          APP_FOLDER: app/build/outputs/apk/debug
          RELEASE_TITLE: Test Release